language: node_js
node_js:
  - 0.10
  - 0.11
  #- iojs # not ready yet, wait for an update here http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/#Schedule
  
notifications:
  irc:
    channels:
      - "irc.freenode.org#cssnext"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
