language: node_js
node_js:
  - 0.10
  - 0.11
  #- iojs not ready yet, wait for 2015-02-03
  
notifications:
  irc:
    channels:
      - "irc.freenode.org#cssnext"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
