# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.10

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g grunt-cli
  - npm install
  - npm uninstall grunt

version: "{build}"
build: off
deploy: off

test_script:
  - node --version
  - npm --version
  - ps: "npm test # PowerShell"
  - cmd: "npm test"
